package com.arcadan.dodgetheenemies.enums

enum class Enemy {
    ALIEN_BLACK,
    ALIEN_BLUE_SHUTTLE,
    ALIEN_FROG,
    ALIEN_WORM,
    BAT,
    BEES,
    BLUE_BIRDS,
    BRANCH_TREE,
    BRANCH_TREE_LEAF,
    BROKEN_WOOD,
    BULLETS,
    BUNNY,
    CACTUS,
    COBRA,
    BULLET_AND_FLAME,
    DRAGON_BIG,
    DRAGON_LITTLE,
    EGGS_RED,
    ROCKS,
    ROCK_BIG,
    ROCK_UPSIDEDOWN,
    SAWS,
    SPIKY_MONSTERS,
    SURFACE_LIANA,
    SNOW_BALL,
    TURTLE_BIG,
    UFOS,
    BOSS_DRAGON,
    STALATTITE,
    FOX,
    RYNO,
    EAGLE,
}
